scrape_configs:
  - job_name: otel_collector_exporter
    scrape_interval: 3s
    static_configs:
      - targets: [ 'otel_collector:8889' ] # application metrics collected by opentelemetry
      - targets: [ 'otel_collector:8888' ] # opentelemetry collector metrics
    